version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.2
    working_directory: ~/terraform
    steps:
      - checkout
      - run:
          name: Initialise Terraform
          command: terraform init -input=false
      - run:
          name: Validate configurations
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (terraform validate -check-variables=false "$m" && echo "âˆš $m") || exit 1 ; done
      - run:
          name: Check if configurations are properly formatted
          command: if [[ -n "$(terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
      - run:
          name: Install tflint (lint checker for Terraform)
          command: curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.4.3/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
      - run:
          name: Check configurations with tflint
          command: tflint
